name: Build Emby Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: 还原依赖项
        run: dotnet restore EmbyActorHeadshotProvider/EmbyActorHeadshotProvider.csproj

      - name: 编译项目
        run: dotnet build EmbyActorHeadshotProvider/EmbyActorHeadshotProvider.csproj --configuration Release --no-restore

      - name: 打包插件
        run: |
          mkdir -p release
          cp EmbyActorHeadshotProvider/bin/Release/net8.0/*.dll release/
          cp EmbyActorHeadshotProvider/bin/Release/net8.0/*.pdb release/

      - name: 上传编译产物到 GitHub Actions 附件
        uses: actions/upload-artifact@v4
        with:
          name: emby-plugin
          path: release/

      - name: 如果是主分支，发布 Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
